name: songci
channels:
- defaults
dependencies:
- pip=9.0.1=py35_1
- python=3.5.2=0
- setuptools=27.2.0=py35_1
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- pip:
  - jieba==0.38
  - pymongo==3.3.1

