name: songci
channels:
- defaults
dependencies:
- pip=9.0.1=py36_1
- python=3.6.1=0
- setuptools=27.2.0=py36_1
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py36_0
- pip:
  - jieba==0.38
  - pymongo==3.3.1
  - pypinyin==0.18.1
